#!/bin/sh
makeversion="make:v2 mk.conf-1:ai"
# Please, do not edit this file.
# Project configuration located in mk.conf

# mk.conf-1 lib
die()   { $log die "$@"; exit 127; }
try()   { eval "$@" || die "try: $@"; }
mklog() { echo -e "\e[1;34m[$1]\e[0m $2" > /dev/stderr; }
# mk.conf-1a lib
check() { for x in $@; do which $x >/dev/null 2>&1 || die "'$x' required"; done; }
cver()  { [ $1 -le 2 ] || die "version not supported"; }
# mk.conf-1i lib
makecc() { $log cc "$@"; $cc $cflags -o $1 $2 -c       || return 1; }
makeld() { $log ld "$@"; $cc -o $1 $2 $ldflags         || return 1; }
makeex() { $log ex "$@"; $cc $cflags -o $1 $2 $ldflags || return 1; }
make() { v=""; while read c; do vc=`$2 "$c"`; v="$v $vc"; mkdir -p $(dirname $vc); try make$1 $vc $c; done; echo $v; }
files() { for f in $(ls src/*.c src/*/*.c 2>/dev/null); do echo $f; done; }
intoobj() { echo "$@" | sed 's/src/obj/' | sed 's/\(\.c\)$/.o/'; }
intobin() { echo "bin/$appname"; }
intoex() { echo "$@" | sed 's/src/bin/' | sed 's/\(\.c\)$/.out/'; }

# load config
try source ./mk.conf
check "$cc"
$target || die "target: $target"

# build
files \
  | make ex intoex  \
  | true # hide output

exit 0
